name: build

on:
  push:
    branches:
      - main
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Set up Python 3.9
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Set up Node 22
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install UCC
        run: |
          python -m pip install --upgrade pip
          python -m pip install splunk-add-on-ucc-framework
          python -m pip install splunk-packaging-toolkit

      - name: Make build script executable
        run: chmod +x scripts/build.sh

      - name: Build add-on
        id: build
        run: |
          ./scripts/build.sh --build
          BUILT_PACKAGE="$(ls -t confluent_addon_for_splunk-*.tar.gz | head -1)"
          echo "built_package=${BUILT_PACKAGE}" >> "$GITHUB_OUTPUT"
          echo "Built package: ${BUILT_PACKAGE}"

      - name: Upload artifact
        uses: actions/upload-artifact@v5
        with:
          name: ${{ steps.build.outputs.built_package }}
          path: ${{ steps.build.outputs.built_package }}
          if-no-files-found: error
